# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0acc0e07df7e69b50ecd02ae592bf1be8b7eb1145f21beace4f68ad9eda156b327c73c7721d0691c14a677cbd0202241946cae258da715ad4582f7bea047ae26

test:
  secret_key_base: 0fcf9576d205357ae45570cbae16b392ac92d0b45c466c48a6f1cef27a8e50fc7ec0e2e26917d2caf5bcf96134b502641592fccbe0fd2bef2b189a32a84c0c3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
